warning: in the working copy of 'prisma.config.ts', LF will be replaced by CRLF the next time Git touches it
[1mdiff --git a/prisma.config.ts b/prisma.config.ts[m
[1mindex 831a20f..d7a7a3c 100644[m
[1m--- a/prisma.config.ts[m
[1m+++ b/prisma.config.ts[m
[36m@@ -1,5 +1,3 @@[m
[31m-// This file was generated by Prisma, and assumes you have installed the following:[m
[31m-// npm install --save-dev prisma dotenv[m
 import "dotenv/config";[m
 import { defineConfig } from "prisma/config";[m
 [m
[36m@@ -7,8 +5,9 @@[m [mexport default defineConfig({[m
   schema: "prisma/schema.prisma",[m
   migrations: {[m
     path: "prisma/migrations",[m
[32m+[m[32m    seed: "tsx prisma/seed.ts",[m
   },[m
   datasource: {[m
     url: process.env["DATABASE_URL"],[m
   },[m
[31m-});[m
[32m+[m[32m});[m
\ No newline at end of file[m
